package com.promising.jarvis.core.awareness;

public enum PlayerEventType {
    JOINED, LEFT, STATE_CHANGED, DIMENSION_CHANGED, RESOURCE_CHANGED,
    HEALTH_CHANGED, FOOD_CHANGED, POSITION_CHANGED, DEATH, RESPAWN,
    ADVANCEMENT_COMPLETED, FIRST_JOIN, NIGHTFALL, HOSTILE_NEARBY, DANGER_DETECTED
}
